### ISSUE TITLE
Temporary way of work

### ISSUE THREAD

**Issue by manusa** [jkubeio/jkube#20]
## Description

Project migration to the Eclipse Foundation is in progress.

In order to be able to continue working on issues and new features, the project has been forked to a different organization https://github.com/jshiftio/jkube.

All PRs fixing issues in this repo should be targeting https://github.com/jshiftio/jkube master branch. Once this project is completely migrated to Eclipse, jshiftio/jkube can then be merged back.

## Tasks to be performed once jshiftio/jkube is merged back
- [x] Deactivate [CircleCI](https://circleci.com/gh/jshiftio/jkube/edit) Sonarcloud integration (jshiftio/jkube is now publishing results to [jkubeio](https://sonarcloud.io/organizations/jkubeio/projects) Sonar organization)

## Other info
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=551219

**Comment by rohanKanojia** [comment]
@manusa : Shall we close this one now? WDYT?

**Comment by manusa** [comment]
Yep, probably. Deleted jshiftio/jkube fork -> CircleCI integration
